### ISSUE TITLE
images dont show 

### ISSUE THREAD

**Issue by siduck76** [alnj/ncmpcpp-ueberzug#5]
images dont show , only fallback image shows help :(  ( st terminal ) 
![e](https://user-images.githubusercontent.com/59060246/101368254-ef0ca800-38cc-11eb-999a-42d3c35328b2.png)

**Comment by siduck76** [comment]
nvm I fixed it and working now thanks :D
![image](https://user-images.githubusercontent.com/59060246/101655967-34b1a800-3a68-11eb-8a35-6b22a16d073e.png)

**Comment by hitagiendmk2** [comment]
> nvm I fixed it and working now thanks :D
> ![image](https://user-images.githubusercontent.com/59060246/101655967-34b1a800-3a68-11eb-8a35-6b22a16d073e.png)

hi, can you share your dotfiles? Mine not showing, even fallback image not showed up either, I have all dependencies installed, I could see mpd_cover.jpg on my tmp folder. thanks
![Screenshot_2021-09-27-02-52-23_2806x900](https://user-images.githubusercontent.com/70511186/134822425-b87dd2c0-23b3-435d-9e5e-f71af9c0e089.png)

**Comment by siduck76** [comment]
@hitagiendmk2  https://github.com/siduck76/dotfiles/tree/master/cli_tools/.ncmpcpp

Make sure your ueberzug is working! check it in ranger first . Also I needed mpc ffmpeg for this to work ._.
