### ISSUE TITLE
[issue] wrapper uses first picture in main directory from the first album directory

### ISSUE THREAD

**Issue by 9ahmed** [alnj/ncmpcpp-ueberzug#7]
![test](https://media.discordapp.net/attachments/635625925748457482/795458540009291796/unknown.png?width=714&height=70)

each one of these album directories are in one main dir ~/Music and each one of them includes a .jpg album cover photo, but it always picks the first picture, in this case its chopin as the first dir so it will use chopin as album art for all the songs in ncmpcpp. When i delete Chopin it uses the album art from GV for all songs, and so on...

**Comment by 9ahmed** [comment]
i use xterm

**Comment by avma** [comment]
Try to run `echo $(mpc --format %file% current)` in your terminal, while you play a song, to check where does it points to. It might give you an idea of what went wrong...

**Comment by 9ahmed** [comment]
it says mpc not found lol

**Comment by 9ahmed** [comment]
i have mpc

**Comment by 9ahmed** [comment]
fixed!
