### ISSUE TITLE
ncmpcpp_cover_art error font size

### ISSUE THREAD

**Issue by KoO-303** [alnj/ncmpcpp-ueberzug#9]
Music Player Daemon 0.22.3 - ncmpcpp 0.9.1

On startup have this error.
Failed to guess font size, try setting it in ncmpcpp_cover_art.sh settings

**Comment by alnj** [comment]
What terminal are you using?
At the time of writing this script, the error would come up in incompatible terminals.
A workaround would be to open ncmpcpp_cover_art.sh and input your font size where indicated, unless you routinely change your terminal font size.

I need to find the time to check if everything still works as expected with the latest ueberzug version.

Check if this person's solution works for you.
https://github.com/alnj/ncmpcpp-ueberzug/issues/8

**Comment by KoO-303** [comment]
Thanks for replying.
Music Player Daemon 0.22.3 , ncmpcpp 0.9.1 , kitty 0.19.3 or rxvt-unicode v9.22  ueberzug 18.1.9
This is on a test version of Debian based antiX bullseye.

Not sure weather it is the antiX 20 test version or the latest versions of mpd , ncmpcpp.

As on antiX 19.2 stable ncmpcpp 0.8.2 mpd 21.5 & kitty everything works and looks amazing.

What I will try when I have time is down grade the versions of mpd and ncmpcpp, on the test version of antiX to ncmpcpp 0.8.2 mpd 21.5 and see is helps.

I also tried https://github.com/alnj/ncmpcpp-ueberzug/issues/8 made no difference.

**Comment by KoO-303** [comment]
By setting the album art font as below it works the way I want.
font_height=150
font_width=70

Music Player Daemon 0.22.4 , ncmpcpp 0.9.2 , kitty 0.19.3 ueberzug 18.1.9


padding_top=40
padding_bottom=15
padding_right=100
max_width=75
reserved_playlist_cols=30
reserved_cols_in_percent="false"
force_square="false"
square_alignment="top"

left_aligned="false"
padding_left=

# Only set this if the geometries are wrong or ncmpcpp shouts at you to do it.
# Visually select/highlight a character on your terminal, zoom in an image 
# editor and count how many pixels a character's width and height are.
font_height=150
font_width=70
